export const structure = [
  [
    {
      name: "알로이시오홀",
      subtitle: "",
      content: "",
      table: "",
      info: "",
    },
    {
      name: "빵굽는수녀님",
      subtitle: "",
      content: "",
      table: "",
      info: "",
    },
    {
      name: "카페바뇌",
      subtitle: "",
      content: "",
      table: "",
      info: "",
    },
    {
      name: "메이커스랩",
      subtitle: "",
      content: "",
      table: "",
      info: "",
    },
    {
      name: "영상제작실",
      subtitle: "",
      content: "",
      table: "",
      info: "",
    },
  ],
  [
    {
      name: "알로이시오역사관",
      subtitle: "",
      content: "",
      table: "",
      info: "",
    },
    {
      name: "뷰티활동실",
      subtitle: "",
      content: "",
      table: "",
      info: "",
    },
    {
      name: "요즘공방",
      subtitle: "",
      content: "",
      table: "",
      info: "",
    },
  ],
  [
    {
      name: "침묵의방",
      subtitle: "",
      content: "",
      table: "",
      info: "",
    },
    {
      name: "작은도서관",
      subtitle: "",
      content: "",
      table: "",
      info: "",
    },
    {
      name: "사랑방",
      subtitle: "",
      content: "",
      table: "",
      info: "",
    },
    {
      name: "생활공방",
      subtitle: "",
      content: "",
      table: "",
      info: "",
    },
    {
      name: "음악활동실",
      subtitle: "",
      content: "",
      table: "",
      info: "",
    },
  ],
  [
    {
      name: "모두의부엌",
      subtitle: "",
      content: "",
      table: "",
      info: "",
    },
    {
      name: "수직농장",
      subtitle: "",
      content: "",
      table: "",
      info: "",
    },
    {
      name: "달빛옥상",
      subtitle: "",
      content: "",
      table: "",
      info: "",
    },
  ],
  [{ name: "옥상텃밭", subtitle: "", content: "", table: "", info: "" }],
];
